"""Tests for bin/codex-rules-sync.

Each test builds fixture rule files in a temp dir, runs the generator via subprocess
with --rules-dir and a temp $CODEX_HOME, and asserts on the written AGENTS.md, the
summary on stdout, and the exit code. Subprocess (not import) matches the repo's
script-testing convention (tests/test_hooks.py) and exercises the real CLI surface.

Classification is a `tool:` frontmatter allowlist, fail-closed: a rule reaches Codex
only when its `tool:` list contains `codex`; absent/other → Claude-only → excluded.
"""

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "bin" / "codex-rules-sync"

GENERATED_FIRST_LINE = (
    "<!-- GENERATED BY codex-rules-sync — DO NOT EDIT MANUALLY. "
    "Run codex-rules-sync to regenerate. -->"
)


def write_rule(
    rules_dir: Path,
    name: str,
    body: str,
    tools: tuple[str, ...] | None = ("claude", "codex"),
) -> None:
    """Write a fixture rule. tools=None → no frontmatter (fail-closed: Codex-excluded)."""
    fm = ""
    if tools is not None:
        fm = f"---\ntool: {', '.join(tools)}\n---\n\n"
    (rules_dir / name).write_text(fm + body)


def run(rules_dir: Path, codex_home: Path, *extra: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(SCRIPT), "--rules-dir", str(rules_dir), *extra],
        capture_output=True,
        text=True,
        env={**os.environ, "CODEX_HOME": str(codex_home)},
    )


@pytest.fixture
def dirs(tmp_path: Path) -> tuple[Path, Path]:
    rules = tmp_path / "rules"
    rules.mkdir()
    home = tmp_path / "codex"
    home.mkdir()
    return rules, home


def test_tool_allowlist_includes_codex_excludes_others(dirs):
    rules, home = dirs
    write_rule(
        rules,
        "portable.md",
        "# Portable\nPORTABLE_SENTINEL\n",
        tools=("claude", "codex"),
    )
    write_rule(
        rules, "claude-only.md", "# Claude Only\nCLAUDE_SENTINEL\n", tools=("claude",)
    )
    write_rule(rules, "untagged.md", "# Untagged\nUNTAGGED_SENTINEL\n", tools=None)

    result = run(rules, home)
    assert result.returncode == 0, result.stderr
    out = (home / "AGENTS.md").read_text()
    assert "PORTABLE_SENTINEL" in out
    assert "CLAUDE_SENTINEL" not in out  # tool: claude → excluded
    assert "UNTAGGED_SENTINEL" not in out  # fail-closed: no tool: key → excluded


def test_tool_mention_in_body_does_not_classify(dirs):
    rules, home = dirs
    # A `tool: codex` mention in the body must not opt a Claude-only rule into Codex —
    # only the frontmatter key counts.
    write_rule(rules, "portable.md", "# P\nPORTABLE_SENTINEL\n")
    write_rule(
        rules,
        "claude-only.md",
        "# Claude Only\nThis rule is for `tool: codex` agents too, someday.\nBODY_SENTINEL\n",
        tools=("claude",),
    )
    result = run(rules, home)
    assert result.returncode == 0, result.stderr
    out = (home / "AGENTS.md").read_text()
    assert "PORTABLE_SENTINEL" in out
    assert "BODY_SENTINEL" not in out


def test_quoted_tool_value_still_parses(dirs):
    rules, home = dirs
    (rules / "quoted.md").write_text(
        '---\ntool: claude, "codex"\n---\n\n# Quoted\nQUOTED_SENTINEL\n'
    )
    result = run(rules, home)
    assert result.returncode == 0, result.stderr
    assert "QUOTED_SENTINEL" in (home / "AGENTS.md").read_text()


def test_comment_after_tool_is_ignored(dirs):
    rules, home = dirs
    # Self-documenting `tool: claude  # harness-only: ...` must parse to just [claude].
    (rules / "harness.md").write_text(
        "---\ntool: claude  # harness-only: a Claude-Code thing\n---\n\n# H\nHARNESS_SENTINEL\n"
    )
    write_rule(rules, "portable.md", "# P\nPORTABLE_SENTINEL\n")
    result = run(rules, home)
    assert result.returncode == 0, result.stderr
    out = (home / "AGENTS.md").read_text()
    assert "PORTABLE_SENTINEL" in out
    assert "HARNESS_SENTINEL" not in out


def test_header_precedence_note_and_source_markers(dirs):
    rules, home = dirs
    write_rule(rules, "alpha.md", "# Alpha\nALPHA_BODY\n")
    result = run(rules, home)
    assert result.returncode == 0, result.stderr
    out = (home / "AGENTS.md").read_text()
    lines = out.splitlines()
    assert lines[0] == GENERATED_FIRST_LINE
    assert "may add to or override" in out  # precedence note
    # rules-dir is a temp dir outside the repo, so the marker uses the fallback
    # `<dir-name>/<file>` form (see test_repo_relative_marker for the in-repo path).
    assert "<!-- from rules/alpha.md -->" in out
    marker_idx = next(i for i, ln in enumerate(lines) if ln.endswith("alpha.md -->"))
    assert lines[marker_idx + 1] == "# Alpha"


def test_repo_relative_marker_for_in_repo_rules():
    # Run over the real rules/common so the source marker exercises the
    # relative_to(ROOT) success path, not just the fallback. --allow-worktree because
    # the default rules-dir lives in this worktree during development.
    rules = ROOT / "rules" / "common"
    with tempfile.TemporaryDirectory() as td:
        result = subprocess.run(
            [
                sys.executable,
                str(SCRIPT),
                "--rules-dir",
                str(rules),
                "--allow-worktree",
            ],
            capture_output=True,
            text=True,
            env={**os.environ, "CODEX_HOME": td},
        )
        assert result.returncode == 0, result.stderr
        out = (Path(td) / "AGENTS.md").read_text()
    assert "<!-- from rules/common/coding-style.md -->" in out


def test_deterministic(dirs):
    rules, home = dirs
    write_rule(rules, "a.md", "# A\nBODY_A\n")
    write_rule(rules, "b.md", "# B\nBODY_B\n", tools=("claude",))
    write_rule(rules, "c.md", "# C\nBODY_C\n", tools=("claude", "codex"))

    assert run(rules, home).returncode == 0
    first = (home / "AGENTS.md").read_text()
    assert run(rules, home).returncode == 0
    second = (home / "AGENTS.md").read_text()
    assert first == second


def test_missing_codex_home_skips_without_writing(dirs):
    rules, _ = dirs
    write_rule(rules, "a.md", "# A\nBODY\n")
    missing = rules.parent / "no-such-codex-home"
    result = run(rules, missing)
    assert result.returncode == 0
    assert "skipping" in result.stdout.lower()
    assert not (missing / "AGENTS.md").exists()
    assert not missing.exists()


def test_codex_home_exists_as_file_errors(dirs):
    rules, _ = dirs
    write_rule(rules, "a.md", "# A\nBODY\n")
    as_file = rules.parent / "codex-as-file"
    as_file.write_text("not a dir")
    result = run(rules, as_file)
    assert result.returncode != 0
    assert "not a directory" in result.stderr.lower()


def test_no_rule_tagged_for_codex_aborts_without_writing(dirs):
    rules, home = dirs
    write_rule(rules, "a.md", "# A\nBODY\n", tools=("claude",))
    write_rule(rules, "b.md", "# B\nBODY\n", tools=None)
    result = run(rules, home)
    assert result.returncode != 0
    assert "no rule is tagged for codex" in result.stderr.lower()
    assert not (home / "AGENTS.md").exists()


def test_abort_does_not_clobber_existing(dirs):
    rules, home = dirs
    existing = home / "AGENTS.md"
    existing.write_text("# KEEP ME\n")
    write_rule(rules, "a.md", "# A\nBODY\n", tools=("claude",))
    result = run(rules, home)
    assert result.returncode != 0
    assert existing.read_text() == "# KEEP ME\n"


def test_summary_reports_counts_and_bytes(dirs):
    rules, home = dirs
    write_rule(rules, "in1.md", "# In1\nX\n")
    write_rule(rules, "in2.md", "# In2\nY\n", tools=("claude", "codex"))
    write_rule(rules, "out.md", "# Out\nZ\n", tools=("claude",))
    result = run(rules, home)
    assert result.returncode == 0, result.stderr
    size = len((home / "AGENTS.md").read_text().encode())
    assert "2 rules included" in result.stdout
    assert "1 excluded" in result.stdout
    assert f"{size} bytes" in result.stdout


def test_unclosed_frontmatter_excluded_and_warns(dirs):
    rules, home = dirs
    write_rule(rules, "good.md", "# Good\nGOOD_SENTINEL\n")
    # Opening `---` with no closing `---`: malformed → fail-closed (Claude-only,
    # excluded from Codex), warn on stderr, and no stray `---` in the output.
    (rules / "weird.md").write_text("---\ntool: claude, codex\nWEIRD_SENTINEL\n")
    result = run(rules, home)
    assert result.returncode == 0, result.stderr
    out = (home / "AGENTS.md").read_text()
    assert "GOOD_SENTINEL" in out
    assert "WEIRD_SENTINEL" not in out
    assert "---" not in out  # no stray horizontal rule from the unclosed block
    assert "no closing" in result.stderr.lower()


def test_list_mode_reports_without_writing(dirs):
    rules, home = dirs
    write_rule(rules, "portable.md", "# P\nBODY\n")
    write_rule(rules, "claude-only.md", "# C\nBODY\n", tools=("claude",))
    result = run(rules, home, "--list")
    assert result.returncode == 0, result.stderr
    assert "include  portable.md" in result.stdout
    assert "exclude  claude-only.md" in result.stdout
    assert not (home / "AGENTS.md").exists()  # --list never writes


def test_list_mode_works_when_nothing_tagged_for_codex(dirs):
    # --list is a diagnostic: it must succeed (not abort) even when no rule is
    # tagged for Codex — that's exactly when you'd run it to find out why.
    rules, home = dirs
    write_rule(rules, "a.md", "# A\nBODY\n", tools=("claude",))
    write_rule(rules, "b.md", "# B\nBODY\n", tools=None)
    result = run(rules, home, "--list")
    assert result.returncode == 0, result.stderr
    assert "0 included" in result.stdout
    assert "exclude  a.md" in result.stdout


@pytest.mark.skipif(
    "/.claude/worktrees/" not in str(SCRIPT),
    reason="worktree guard only triggers from a worktree checkout",
)
def test_worktree_guard_refuses_default_rules(tmp_path):
    # No --rules-dir (so it uses the in-worktree default) and no --allow-worktree:
    # the generator must refuse rather than clobber the machine-global AGENTS.md.
    home = tmp_path / "codex"
    home.mkdir()
    result = subprocess.run(
        [sys.executable, str(SCRIPT)],
        capture_output=True,
        text=True,
        env={**os.environ, "CODEX_HOME": str(home)},
    )
    assert result.returncode != 0
    assert "worktree" in result.stderr.lower()
    assert not (home / "AGENTS.md").exists()


@pytest.mark.skipif(shutil.which("codex") is None, reason="codex binary not installed")
def test_codex_loads_global_file_head_and_tail(dirs):
    rules, home = dirs
    # Distinct head and tail sentinels (sorted filenames put aaa first, zzz last).
    write_rule(rules, "aaa.md", "# AAA\nHEAD_SENTINEL_8f3a\n")
    write_rule(rules, "zzz.md", "# ZZZ\nTAIL_SENTINEL_2c91\n")
    assert run(rules, home).returncode == 0

    proc = subprocess.run(
        ["codex", "debug", "prompt-input"],
        capture_output=True,
        text=True,
        cwd=str(home.parent),
        env={**os.environ, "CODEX_HOME": str(home)},
    )
    combined = proc.stdout + proc.stderr
    assert "HEAD_SENTINEL_8f3a" in combined
    assert "TAIL_SENTINEL_2c91" in combined
