"""Tests for bin/opencode-skills-commands-sync."""

import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "bin" / "opencode-skills-commands-sync"
SUBPROCESS_TIMEOUT_SECONDS = 30


def write_skill(
    skills_dir: Path,
    name: str,
    *,
    invocable: bool = True,
    description: str | None = None,
) -> None:
    skill_dir = skills_dir / name
    skill_dir.mkdir(parents=True)
    description = description or f"Run {name}."
    skill_dir.joinpath("SKILL.md").write_text(
        "---\n"
        f"name: {name}\n"
        f"description: {description}\n"
        f"user-invocable: {'true' if invocable else 'false'}\n"
        "---\n\n"
        f"# {name}\n\nUse $ARGUMENTS.\n"
    )


def run(repo_dir: Path, commands_dir: Path, *extra: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--repo-dir",
            str(repo_dir),
            "--commands-dir",
            str(commands_dir),
            *extra,
        ],
        capture_output=True,
        text=True,
        env=os.environ,
        timeout=SUBPROCESS_TIMEOUT_SECONDS,
    )


def test_generates_commands_for_user_invocable_skills(tmp_path: Path):
    repo = tmp_path / "repo"
    skills_dir = repo / "skills"
    write_skill(skills_dir, "mine-debug", invocable=True)
    write_skill(skills_dir, "internal-reference", invocable=False)
    commands = tmp_path / "commands"

    result = run(repo, commands)

    assert result.returncode == 0, result.stderr
    out = (commands / "mine-debug.md").read_text()
    assert "GENERATED BY opencode-skills-commands-sync" in out
    assert "Load and follow the OpenCode skill named `mine-debug`" in out
    assert "$ARGUMENTS" in out
    assert not (commands / "internal-reference.md").exists()


def test_unescapes_quoted_skill_descriptions(tmp_path: Path):
    repo = tmp_path / "repo"
    write_skill(
        repo / "skills",
        "mine-debug",
        description='"Use when the user says: \\"debug this\\"."',
    )
    commands = tmp_path / "commands"

    result = run(repo, commands)

    assert result.returncode == 0, result.stderr
    out = (commands / "mine-debug.md").read_text()
    assert 'description: "Use when the user says: \\"debug this\\"."' in out
    assert '\\\\"debug this' not in out


def test_list_prints_without_writing(tmp_path: Path):
    repo = tmp_path / "repo"
    write_skill(repo / "skills", "mine-debug")
    commands = tmp_path / "commands"

    result = run(repo, commands, "--list")

    assert result.returncode == 0
    assert "mine-debug" in result.stdout
    assert not commands.exists()


def test_refuses_to_clobber_handwritten_command(tmp_path: Path):
    repo = tmp_path / "repo"
    write_skill(repo / "skills", "mine-debug")
    commands = tmp_path / "commands"
    commands.mkdir()
    target = commands / "mine-debug.md"
    target.write_text("# Hand written\n")

    result = run(repo, commands)

    assert result.returncode != 0
    assert "not generated by this tool" in result.stderr
    assert target.read_text() == "# Hand written\n"


def test_removes_stale_generated_command(tmp_path: Path):
    repo = tmp_path / "repo"
    write_skill(repo / "skills", "mine-debug")
    commands = tmp_path / "commands"
    commands.mkdir()
    stale = commands / "old-skill.md"
    stale.write_text(
        "<!-- GENERATED BY opencode-skills-commands-sync — DO NOT EDIT MANUALLY. -->\n"
    )

    result = run(repo, commands)

    assert result.returncode == 0, result.stderr
    assert not stale.exists()
    assert (commands / "mine-debug.md").exists()


def test_can_generate_from_installed_skills_dir(tmp_path: Path):
    repo = tmp_path / "repo"
    write_skill(repo / "skills", "repo-only")
    installed = tmp_path / "installed-skills"
    write_skill(installed, "installed-skill")
    commands = tmp_path / "commands"

    result = run(
        repo,
        commands,
        "--skills-dir",
        str(installed),
        "--skill-base-path",
        "/custom/claude/skills",
    )

    assert result.returncode == 0, result.stderr
    assert not (commands / "repo-only.md").exists()
    out = (commands / "installed-skill.md").read_text()
    assert "/custom/claude/skills/installed-skill/SKILL.md" in out


def test_remove_generated_preserves_handwritten_commands(tmp_path: Path):
    repo = tmp_path / "repo"
    commands = tmp_path / "commands"
    commands.mkdir()
    generated = commands / "mine-debug.md"
    generated.write_text(
        "<!-- GENERATED BY opencode-skills-commands-sync — DO NOT EDIT MANUALLY. -->\n"
    )
    handwritten = commands / "handwritten.md"
    handwritten.write_text("# Keep\n")

    result = run(repo, commands, "--remove-generated")

    assert result.returncode == 0, result.stderr
    assert not generated.exists()
    assert handwritten.read_text() == "# Keep\n"


def test_missing_explicit_skills_dir_errors_before_cleanup(tmp_path: Path):
    repo = tmp_path / "repo"
    commands = tmp_path / "commands"
    commands.mkdir()
    generated = commands / "mine-debug.md"
    generated.write_text(
        "<!-- GENERATED BY opencode-skills-commands-sync — DO NOT EDIT MANUALLY. -->\n"
    )

    result = run(repo, commands, "--skills-dir", str(tmp_path / "missing"))

    assert result.returncode != 0
    assert "skills dir does not exist" in result.stderr
    assert generated.exists()


def test_empty_skill_set_refuses_to_remove_generated_wrappers(tmp_path: Path):
    repo = tmp_path / "repo"
    skills = tmp_path / "installed-skills"
    skills.mkdir()
    commands = tmp_path / "commands"
    commands.mkdir()
    generated = commands / "mine-debug.md"
    generated.write_text(
        "<!-- GENERATED BY opencode-skills-commands-sync — DO NOT EDIT MANUALLY. -->\n"
    )

    result = run(repo, commands, "--skills-dir", str(skills))

    assert result.returncode != 0
    assert "no user-invocable skills found" in result.stderr
    assert generated.exists()
