"""Tests for bin/lint-agent-models.

The script is both the generator and the pre-commit gate for two artifacts
derived from agent frontmatter: rules/common/performance.md's agent list and
install.py's per-bundle `agents=(...)` tuples. These tests build a minimal
fixture repo under tmp_path (agents/, rules/common/performance.md,
install.py) rather than touching the real repo, and drive the script through
`--root` so generation and staleness checks run against the fixture.
"""

import runpy
from pathlib import Path

import pytest

SCRIPT = Path(__file__).resolve().parent.parent / "bin" / "lint-agent-models"

PERFORMANCE_MD_FIXTURE = """# Model Selection

## Agent Model Declarations

Generated section below.

**Agent files:**
<!-- GENERATED BY bin/lint-agent-models -- DO NOT EDIT MANUALLY. Run `bin/lint-agent-models --write` to regenerate. -->
<!-- END GENERATED -->
"""

INSTALL_PY_FIXTURE = """def get_bundles():
    return {
        "base": Bundle(
            label="Base",
            agents=(
                "foo",
                "bar",
            ),
        ),
        "extra": Bundle(
            label="Extra",
            agents=("baz",),
        ),
    }
"""


def _load_script() -> dict:
    return runpy.run_path(str(SCRIPT), run_name="_test_lint_agent_models")


def _write_agent(
    agents_dir: Path,
    stem: str,
    *,
    model: str = "sonnet",
    effort: str = "high",
    bundle: str = "base",
    model_comment: str = "",
    include_fields: tuple[str, ...] = (
        "model",
        "effort",
        "tools",
        "description",
        "bundle",
    ),
) -> None:
    """Write agents/<stem>.md with the given frontmatter fields.

    `include_fields` lets a test omit one required field to exercise the
    completeness check; the omitted field's line is simply not written.
    """
    fields = {
        "model": f"model: {model}{model_comment}",
        "effort": f"effort: {effort}",
        "tools": 'tools: ["Read"]',
        "description": f"description: {stem} test agent.",
        "bundle": f"bundle: {bundle}",
    }
    lines = ["---", f"name: {stem}"]
    lines += [fields[f] for f in include_fields]
    lines += ["---", "", f"# {stem}", "", "Body."]
    (agents_dir / f"{stem}.md").write_text("\n".join(lines) + "\n")


def _build_fixture_repo(root: Path) -> None:
    (root / "agents").mkdir(parents=True)
    (root / "rules" / "common").mkdir(parents=True)
    _write_agent(root / "agents", "foo", bundle="base")
    _write_agent(root / "agents", "bar", bundle="base")
    _write_agent(root / "agents", "baz", bundle="extra")
    (root / "rules" / "common" / "performance.md").write_text(PERFORMANCE_MD_FIXTURE)
    (root / "install.py").write_text(INSTALL_PY_FIXTURE)


def test_generation_is_idempotent(tmp_path: Path) -> None:
    """A second --write with no frontmatter changes produces byte-identical output."""
    _build_fixture_repo(tmp_path)
    module = _load_script()

    assert module["main"](["--root", str(tmp_path), "--write"]) == 0
    perf_after_first = (tmp_path / "rules" / "common" / "performance.md").read_text()
    install_after_first = (tmp_path / "install.py").read_text()

    assert module["main"](["--root", str(tmp_path), "--write"]) == 0
    assert (
        tmp_path / "rules" / "common" / "performance.md"
    ).read_text() == perf_after_first
    assert (tmp_path / "install.py").read_text() == install_after_first

    # And check mode (no --write) is clean against what --write produced.
    assert module["main"](["--root", str(tmp_path)]) == 0


def test_generation_produces_expected_content(tmp_path: Path) -> None:
    _build_fixture_repo(tmp_path)
    module = _load_script()

    assert module["main"](["--root", str(tmp_path), "--write"]) == 0

    perf_text = (tmp_path / "rules" / "common" / "performance.md").read_text()
    assert "- `agents/bar.md` — sonnet, high" in perf_text
    assert "- `agents/baz.md` — sonnet, high" in perf_text
    assert "- `agents/foo.md` — sonnet, high" in perf_text

    install_text = (tmp_path / "install.py").read_text()
    assert '"foo"' in install_text and '"bar"' in install_text
    assert '"baz"' in install_text
    # baz belongs to the "extra" bundle, not "base".
    base_block = install_text.split('"base": Bundle(')[1].split('"extra": Bundle(')[0]
    assert '"baz"' not in base_block


def test_model_comment_annotation_reproduced(tmp_path: Path) -> None:
    """An em-dash-separated trailing comment on model: becomes a parenthetical."""
    _build_fixture_repo(tmp_path)
    _write_agent(
        tmp_path / "agents",
        "foo",
        bundle="base",
        model_comment="  # claude-sonnet-5 as of 2026-07-07 — do not downgrade; pre-commit safety gate",
    )
    module = _load_script()

    assert module["main"](["--root", str(tmp_path), "--write"]) == 0

    perf_text = (tmp_path / "rules" / "common" / "performance.md").read_text()
    assert (
        "- `agents/foo.md` — sonnet, high (do not downgrade; pre-commit safety gate)"
        in perf_text
    )


def test_staleness_check_fires_on_mutated_artifact(tmp_path: Path) -> None:
    """Hand-editing a generated artifact without regenerating fails check mode."""
    _build_fixture_repo(tmp_path)
    module = _load_script()
    assert module["main"](["--root", str(tmp_path), "--write"]) == 0

    perf_path = tmp_path / "rules" / "common" / "performance.md"
    perf_path.write_text(
        perf_path.read_text().replace("sonnet, high", "sonnet, medium")
    )

    assert module["main"](["--root", str(tmp_path)]) == 1


def test_staleness_check_fires_on_unregenerated_frontmatter_change(
    tmp_path: Path,
) -> None:
    """Changing an agent's frontmatter without running --write fails check mode."""
    _build_fixture_repo(tmp_path)
    module = _load_script()
    assert module["main"](["--root", str(tmp_path), "--write"]) == 0

    _write_agent(tmp_path / "agents", "foo", model="haiku", bundle="base")

    assert module["main"](["--root", str(tmp_path)]) == 1


@pytest.mark.parametrize(
    "missing_field", ["model", "effort", "tools", "description", "bundle"]
)
def test_completeness_check_names_missing_field(
    tmp_path: Path, capsys: pytest.CaptureFixture, missing_field: str
) -> None:
    _build_fixture_repo(tmp_path)
    all_fields = ("model", "effort", "tools", "description", "bundle")
    _write_agent(
        tmp_path / "agents",
        "foo",
        include_fields=tuple(f for f in all_fields if f != missing_field),
    )
    module = _load_script()

    result = module["main"](["--root", str(tmp_path)])
    output = capsys.readouterr()

    assert result == 1
    assert "agents/foo.md" in output.err
    assert missing_field in output.err


def test_write_mode_reports_up_to_date_when_nothing_changed(
    tmp_path: Path, capsys: pytest.CaptureFixture
) -> None:
    _build_fixture_repo(tmp_path)
    module = _load_script()
    assert module["main"](["--root", str(tmp_path), "--write"]) == 0
    capsys.readouterr()

    assert module["main"](["--root", str(tmp_path), "--write"]) == 0
    output = capsys.readouterr()
    assert "already up to date" in output.out
